print("Hello, World!")
print(5+3)
print("Python", "is", "fun!")
print("She said,\"hello!\"")
print("First line\nSecound line")
print("Item 1\titem 2\titem 3")
print("The result is",42)
print(12345)
print(3.14159)
print("Dollar sign:$")
print("apple","banana","cherry", sep=",")
print("hello,",end="")
print("world!")
print("python!"*3)
print("\u2764") # prints a heart symbol
